name: $(Build.DefinitionName)-$(Date:yyyy-MM-dd).$(Rev:rr)B

trigger:
  batch: true
  branches:
    include:
    - master

resources:
  repositories:
  - repository: pipelines
    type: git
    name: 000.HAV-Pipelines
    ref: master
    trigger: none

extends:
  template: 000.HAV-Bonusario/Builds/000.HAV-Bonusario.yml@pipelines
