//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Havit.Bonusario.DataLayer.DataEntries.Common;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class ApplicationSettingsEntries : Havit.Data.Patterns.DataEntries.DataEntries<Havit.Bonusario.Model.Common.ApplicationSettings>, IApplicationSettingsEntries 
{
	private Havit.Bonusario.Model.Common.ApplicationSettings current;

	public Havit.Bonusario.Model.Common.ApplicationSettings Current => current ??= GetEntry(Havit.Bonusario.Model.Common.ApplicationSettings.Entry.Current);

	public ApplicationSettingsEntries(Havit.Bonusario.DataLayer.Repositories.Common.IApplicationSettingsRepository repository)
		: base(repository)
	{
	}
}
