//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Havit.Bonusario.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakePeriodDataSource : FakeDataSource<Havit.Bonusario.Model.Period>, Havit.Bonusario.DataLayer.DataSources.IPeriodDataSource
{
	public FakePeriodDataSource(params Havit.Bonusario.Model.Period[] data)
		: this((IEnumerable<Havit.Bonusario.Model.Period>)data)
	{			
	}

	public FakePeriodDataSource(IEnumerable<Havit.Bonusario.Model.Period> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
