//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Havit.Bonusario.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeEntryTagDataSource : FakeDataSource<Havit.Bonusario.Model.EntryTag>, Havit.Bonusario.DataLayer.DataSources.IEntryTagDataSource
{
	public FakeEntryTagDataSource(params Havit.Bonusario.Model.EntryTag[] data)
		: this((IEnumerable<Havit.Bonusario.Model.EntryTag>)data)
	{			
	}

	public FakeEntryTagDataSource(IEnumerable<Havit.Bonusario.Model.EntryTag> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
