//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Havit.Bonusario.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeEntryDataSource : FakeDataSource<Havit.Bonusario.Model.Entry>, Havit.Bonusario.DataLayer.DataSources.IEntryDataSource
{
	public FakeEntryDataSource(params Havit.Bonusario.Model.Entry[] data)
		: this((IEnumerable<Havit.Bonusario.Model.Entry>)data)
	{			
	}

	public FakeEntryDataSource(IEnumerable<Havit.Bonusario.Model.Entry> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
